
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    systemctl reload sshd
    echo -e "admin\nadmin" | passwd root > /dev/null 2>&1
  SHELL

  config.vm.define "master3" do | node |
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = "master3"
    node.vm.network "private_network", ip: "172.16.16.213"
    node.vm.provider "virtualbox" do | v |
      v.name = "master3"
      v.memory = "2048"
      v.cpus = 2
    end
  end

  config.vm.define "worker3" do | node |
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = "worker3"
    node.vm.network "private_network", ip: "172.16.16.223"
    node.vm.provider "virtualbox" do | v |
      v.name = "worker3"
      v.memory = 1024
      v.cpus = 1
    end
  end
end
