
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    systemctl reload sshd
    echo -e "admin\nadmin" | passwd root > /dev/null 2>&1
  SHELL

  # HAproxy load balancer node
  config.vm.define "haproxy" do | node |
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostname = "haproxy"
    node.vm.network "private_network", ip: "172.16.16.200"
    node.vm.provider "virtualbox" do | vb |
      vb.name = "haproxy"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Master node
  (1..2).each do | i |
    config.vm.define "master#{i}" do | node |
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "master#{i}"
      node.vm.network "private_network", ip: "172.16.16.21#{i}"
      node.vm.provider "virtualbox" do | vb |
        vb.name = "master#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end

  # Worker node
  (1..3).each do | i |
    config.vm.define "worker#{i}" do | node |
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "worker#{i}"
      node.vm.network "private_network", ip: "172.16.16.22#{i}"
      node.vm.provider "virtualbox" do | vb |
        vb.name = "worker#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

end
